#!/bin/bash

sketchybar --add event rift_workspace_changed

# Determine how many monitors are connected once
MONITOR_COUNT=$(rift-cli query displays | jq -r '.[] | .screen_id' | wc -l)

for monitor in $(rift-cli query displays | jq -r '.[] | .screen_id'); do
  for sid in $(rift-cli query workspaces | jq -r '.[] | .index'); do
    # Label is sid which if it contains more than a number it should strip out the number in front
    label="$sid"
    # Strip only leading digits
    icon="$(rift-cli query workspaces | jq -r '.['$sid'] | .name' | sed -E 's/^[0-9]+//')"
    # Set background based on focused item, focused background should be 0x88cc5500
    if [ "$(rift-cli query workspaces | jq '.[] | select(.is_active == true) | .index')" = "$sid" ]; then
      background=0x88cc5500
    else
      background=0x22f0f0f0
    fi

    echo "Adding workspace $sid with label $label ($icon) on monitor $monitor"
    sketchybar --add item space.$sid left \
        --subscribe space.$sid rift_workspace_changed display_changed system_woke \
        --set space.$sid \
        background.color="$background" \
        background.corner_radius=5 \
        background.height=20 \
        label.font.family="Hack Nerd Font" \
        label.font.size=8 \
        label.color=0xccf0f0f0 \
        icon.padding_left=4 \
        icon.padding_right=0 \
	      icon="$icon" \
        label="$label" \
        label.y_offset=-6 \
        label.padding_left=4 \
        label.padding_right=4 \
        click_script="rift-cli execute workspace switch $sid" \
        script="$CONFIG_DIR/plugins/rift.sh $sid"
  done
done

# Add a periodic workspace sync item
#sketchybar --add item workspace_sync center \
#           --set workspace_sync update_freq=5 \
#                 drawing=off \
#                 script="$PLUGIN_DIR/rift.sh"

sketchybar --trigger rift_workspace_changed FOCUSED_WORKSPACE=$(rift-cli query workspaces | jq '.[] | select(.is_active == true) | .index')
