#!/bin/bash

set -e

RIFT_CLI="/Users/briankaplan/.bin/rift-cli"

sketchybar --add event rift_workspace_changed

$RIFT_CLI query displays | jq -r '.[] | @json' | while IFS= read -r monitor_json; do
  space_id=$(echo $monitor_json | jq -r '.space');
  $RIFT_CLI query workspaces --space-id $space_id | jq -r '.[] | @json' | while IFS= read -r workspace_json; do
      sid=$(echo $workspace_json | jq -r '.name' | grep -o '[0-9]')
      echo $workspace_json | hexdump -C
      echo "SID: "$sid | hexdump -C
      window_count=$(echo $workspace_json | jq -r '.window_count')
      #if [[ "$window_count" == "0" ]]; then
      #  continue
      #fi
      # Label is sid which if it contains more than a number it should strip out the number in front
      label="$sid"
      # Strip only leading digits
      icon=$(echo $workspace_json | jq -r '.name' | sed -E 's/^[0-9]+//')
      if [ -z "$sid" ]; then
        continue
      fi
      echo "$icon" | hexdump -C
      echo "$monitor_json" | hexdump -C
      display_uuid=$(echo $monitor_json | jq -r '.uuid');
      display_space=$(echo $monitor_json | jq -r '.space');
      monitor=$(sketchybar --query displays | jq -r '.[] | select(.UUID == "'$display_uuid'") | ."arrangement-id"');
      sketchy_item=$(sketchybar --query item space.$sid.$monitor | jq -r)
      echo "SKETCHY_ITEM:" space"."$sid"."$monitor" "$sketchy_item
      if [ -n "$sketchy_item" ]; then
        continue
      fi
      echo "$monitor" | hexdump -C
      echo "$display_uuid" | hexdump -C
      echo "$display_space" | hexdump -C
      if [ -z "$monitor" ] || [ -z "$display_uuid" ] || [ -z "$display_space" ]; then
        continue
      fi
      workspace=$($RIFT_CLI query workspaces --space-id "$display_space")
      # Set background based on focused item, focused background should be 0x88cc5500
      if [ "$(echo $workspace | jq -jr '.[] | select(.is_active) | .index')" = "$sid" ]; then
        background=0x88cc5500
      else
        background=0x22f0f0f0
      fi
      echo "WORKSPACE:" $workspace | hexdump -C
      # strip leading digits from name for icon
      echo "Adding workspace $sid with label $label ($icon) on monitor $monitor"
      sketchybar --add item space.$sid.$monitor left display=$monitor \
          --subscribe space.$sid.$monitor rift_workspace_changed display_change system_woke \
          --set space.$sid.$monitor \
          display=$monitor \
          background.color="$background" \
          background.corner_radius=5 \
          background.height=20 \
          label.font.family="Hack Nerd Font" \
          label.font.size=8 \
          label.color=0xccf0f0f0 \
          icon.padding_left=4 \
          icon.padding_right=0 \
          icon="$icon" \
          label="$label" \
          label.y_offset=-6 \
          label.padding_left=4 \
          label.padding_right=4 \
          click_script="$RIFT_CLI execute workspace switch $sid" \
          script="$CONFIG_DIR/plugins/rift.sh $sid"
    done
done
